const list = {
    devices : [
        { name: 'Display', value: 'display' },
        { name: 'Mobile', value: 'mobile' },
        { name: 'Video', value: 'Video' }
    ],
    templates : [
        { name: 'Báo Dân Trí', value: 'dantri-pc', type: 'display' },
        { name: 'Báo Phụ Nữ Today', value: 'phunutoday-pc', type: 'display' },
        { name: 'Báo Thể Thao 247', value: 'thethao247-pc', type: 'display' },
        { name: 'Báo Dân Trí', value: 'dantri-mb', type: 'mobile' },
        { name: 'Báo Phụ Nữ Today', value: 'phunutoday-mb', type: 'mobile' },
        { name: 'Báo Thể Thao 247', value: 'thethao247-mb', type: 'mobile' },
    ],
    adformats : [
        { name: 'Display Masthead (Billboard)', value: 'billboard', type: 'display' },
        { name: 'Display Balloon Expandable', value: 'balloon', type: 'display' },
        { name: 'Display Bottom Up Expandable', value: 'bottom-up', type: 'display' },
        { name: 'Display In Image', value: 'in-native', type: 'display' },
        { name: 'Display In Image Takeover', value: 'in-takeover', type: 'display' },
        { name: 'Display In Image Carousel', value: 'in-carousel', type: 'display' },
        { name: 'Display In Image With Inread Video', value: 'in-inread', type: 'display' },
        { name: 'Display On Image', value: 'on-image-pc', type: 'display' },
        { name: 'Display 3D Post Carousel', value: '3d-post-carousel', type: 'display' },
        { name: 'Mobile Masthead', value: 'masthead-mb', type: 'mobile' },
        { name: 'Mobile Interscroller (Inpage)', value: 'inpage', type: 'mobile' },
        { name: 'Mobile Interstitial (Firstview)', value: 'firstview', type: 'mobile' },
        { name: 'Mobile Footer Expandable', value: 'footer', type: 'mobile' },
        { name: 'Mobile In Image', value: 'in-native', type: 'mobile' },
        { name: 'Mobile In Image Takeover', value: 'in-takeover', type: 'mobile' },
        { name: 'Mobile In Image Carousel', value: 'in-carousel', type: 'mobile' },
        { name: 'Mobile On Image With Inread Video', value: 'in-inread', type: 'mobile' },
        { name: 'Mobile On Image', value: 'on-image-mb', type: 'mobile' },
        { name: 'Mobile 3D Post Carousel', value: '3d-post-carousel', type: 'mobile' },
    ],
    domains : [
        { name: 'Demo', value: 'https://demo.yomedia.vn/' },
        { name: 'Media', value: 'https://media.yomedia.vn/' },
    ],
}